### ISSUE TITLE
Errors only showing on console

### ISSUE THREAD

**Issue by lord-enzo** [benedfit/SublimeLinter-contrib-jade-lint#8]
The errors are only listed in the console, not on the line number column or the file itself

**Comment by christophervoigt** [comment]
I think I got the same problem, was there a solution?

Sublime Linter, SublimeLinter-pug-lint and pug-lint are all installed (see versions below).
After that in my pug files nothing get's highlighted, even if make intentional failures. (eslint, stylelint or annotations work fine)

If I open the ST console and do changes in my pug file, I see that the linter runs and logs errors in the console, but it still doesn't highlight any errors in the code.

Could this be related or is it something that needs a separat issue?

`SublimeLinter`: 4.11.3
`SublimeLinter-pug-lint`: 1.2.0
`pug-lint`: 2.6.0
`ST3`: 3207
